# do a trace (get more output to log), true or false
do_trace = false

# file that you write your log to
own_log = "/var/log/tibber2mptt.log"

# login data of your ftp server
tibberurl = "https://api.tibber.com/v1-beta/gql"
tibbertoken = "<token>"
